# Generated by Django 3.2.12 on 2023-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_good_options'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='good',
        ),
        migrations.AddField(
            model_name='service',
            name='good',
            field=models.ManyToManyField(related_name='services', to='goods.Good', verbose_name='Товары'),
        ),
    ]
