# Generated by Django 3.2.12 on 2023-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='model',
            field=models.CharField(default='NoName', max_length=255, verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
