# Generated by Django 3.2.12 on 2023-06-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_good_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный товар'),
        ),
    ]
