# Generated by Django 3.2.12 on 2023-06-01 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_alter_good_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_auto_20230601_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ManyToManyField(to='services.Service', verbose_name='Услуги')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='cart.cart', verbose_name='Корзина')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.good', verbose_name='Товар')),
            ],
        ),
    ]
